global using System;
global using System.Linq;
global using Microsoft.AspNetCore.Builder;
global using System.Threading.Tasks;
global using Microsoft.AspNetCore.Mvc;
global using System.Collections.Generic;
global using Chamados.Service.Domain.Entidades;
global using Chamados.Service.Domain.Interfaces.Servicos;
global using Chamados.Service.Domain.Interfaces.Repositorios;