name: Build-Tests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  TESTS_PROJECT_PATH: ./test
  PROJECT_PATH: ./test/Chamados.Service.Tests.csproj
  NUGET_SERVER: https://api.nuget.org/v3/index.json

jobs:
  Build-Test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2.3.4
    - name: Setup .NET 6
      uses: actions/setup-dotnet@v1.7.2
      with:
        dotnet-version: 6.0.x
        
    - name: Restore Dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --no-restore

    - name: MSTest+Coverlet
      run: dotnet test ${{ env.PROJECT_PATH }} 
      
#      --logger:"html;LogFileName=resultado-testes.html"

    - name: Install ReportGenerator
      if: always()
      run: dotnet tool install --global dotnet-reportgenerator-globaltool --version 4.8.6
  
    - name: Upload UnitTest and Cover Reports as Artifacts
      uses: actions/upload-artifact@v2.2.2
      env:
        TESTS_PROJECT_PATH: ${{ env.TESTS_PROJECT_PATH }}/TestResults/
      if: always()
      with:
        name: resultado-testes
        path: ${{ env.TESTS_PROJECT_PATH }}
        retention-days: 30